// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokémonDV.Api.Models;

namespace PokémonDV.Api.Migrations
{
    [DbContext(typeof(PokémonContext))]
    partial class PokémonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokémonDV.Api.Models.BaseStatSet", b =>
                {
                    b.Property<byte>("PokédexId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Attack")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Defense")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Special")
                        .HasColumnType("tinyint");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint");

                    b.HasKey("PokédexId");

                    b.ToTable("BaseStats");

                    b.HasData(
                        new
                        {
                            PokédexId = (byte)1,
                            Attack = (byte)49,
                            Defense = (byte)49,
                            HP = (byte)45,
                            Special = (byte)65,
                            Species = "Bulbasaur",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)2,
                            Attack = (byte)62,
                            Defense = (byte)63,
                            HP = (byte)60,
                            Special = (byte)80,
                            Species = "Ivysaur",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)3,
                            Attack = (byte)82,
                            Defense = (byte)83,
                            HP = (byte)80,
                            Special = (byte)100,
                            Species = "Venusaur",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)4,
                            Attack = (byte)52,
                            Defense = (byte)43,
                            HP = (byte)39,
                            Special = (byte)50,
                            Species = "Charmander",
                            Speed = (byte)65
                        },
                        new
                        {
                            PokédexId = (byte)5,
                            Attack = (byte)64,
                            Defense = (byte)58,
                            HP = (byte)58,
                            Special = (byte)65,
                            Species = "Charmeleon",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)6,
                            Attack = (byte)84,
                            Defense = (byte)78,
                            HP = (byte)78,
                            Special = (byte)85,
                            Species = "Charizard",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)7,
                            Attack = (byte)48,
                            Defense = (byte)65,
                            HP = (byte)44,
                            Special = (byte)50,
                            Species = "Squirtle",
                            Speed = (byte)43
                        },
                        new
                        {
                            PokédexId = (byte)8,
                            Attack = (byte)63,
                            Defense = (byte)80,
                            HP = (byte)59,
                            Special = (byte)65,
                            Species = "Wartortle",
                            Speed = (byte)58
                        },
                        new
                        {
                            PokédexId = (byte)9,
                            Attack = (byte)83,
                            Defense = (byte)100,
                            HP = (byte)79,
                            Special = (byte)85,
                            Species = "Blastoise",
                            Speed = (byte)78
                        },
                        new
                        {
                            PokédexId = (byte)10,
                            Attack = (byte)30,
                            Defense = (byte)35,
                            HP = (byte)45,
                            Special = (byte)20,
                            Species = "Caterpie",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)11,
                            Attack = (byte)20,
                            Defense = (byte)55,
                            HP = (byte)50,
                            Special = (byte)25,
                            Species = "Metapod",
                            Speed = (byte)30
                        },
                        new
                        {
                            PokédexId = (byte)12,
                            Attack = (byte)45,
                            Defense = (byte)50,
                            HP = (byte)60,
                            Special = (byte)80,
                            Species = "Butterfree",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)13,
                            Attack = (byte)35,
                            Defense = (byte)30,
                            HP = (byte)40,
                            Special = (byte)20,
                            Species = "Weedle",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)14,
                            Attack = (byte)25,
                            Defense = (byte)50,
                            HP = (byte)45,
                            Special = (byte)25,
                            Species = "Kakuna",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)15,
                            Attack = (byte)80,
                            Defense = (byte)40,
                            HP = (byte)65,
                            Special = (byte)45,
                            Species = "Beedrill",
                            Speed = (byte)75
                        },
                        new
                        {
                            PokédexId = (byte)16,
                            Attack = (byte)45,
                            Defense = (byte)40,
                            HP = (byte)40,
                            Special = (byte)35,
                            Species = "Pidgey",
                            Speed = (byte)56
                        },
                        new
                        {
                            PokédexId = (byte)17,
                            Attack = (byte)60,
                            Defense = (byte)55,
                            HP = (byte)63,
                            Special = (byte)50,
                            Species = "Pidgeotto",
                            Speed = (byte)71
                        },
                        new
                        {
                            PokédexId = (byte)18,
                            Attack = (byte)80,
                            Defense = (byte)75,
                            HP = (byte)83,
                            Special = (byte)70,
                            Species = "Pidgeot",
                            Speed = (byte)91
                        },
                        new
                        {
                            PokédexId = (byte)19,
                            Attack = (byte)56,
                            Defense = (byte)35,
                            HP = (byte)30,
                            Special = (byte)25,
                            Species = "Rattata",
                            Speed = (byte)72
                        },
                        new
                        {
                            PokédexId = (byte)20,
                            Attack = (byte)81,
                            Defense = (byte)60,
                            HP = (byte)55,
                            Special = (byte)50,
                            Species = "Raticate",
                            Speed = (byte)97
                        },
                        new
                        {
                            PokédexId = (byte)21,
                            Attack = (byte)60,
                            Defense = (byte)30,
                            HP = (byte)40,
                            Special = (byte)31,
                            Species = "Spearow",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)22,
                            Attack = (byte)90,
                            Defense = (byte)65,
                            HP = (byte)65,
                            Special = (byte)61,
                            Species = "Fearow",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)23,
                            Attack = (byte)60,
                            Defense = (byte)44,
                            HP = (byte)35,
                            Special = (byte)40,
                            Species = "Ekans",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)24,
                            Attack = (byte)85,
                            Defense = (byte)69,
                            HP = (byte)60,
                            Special = (byte)65,
                            Species = "Arbok",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)25,
                            Attack = (byte)55,
                            Defense = (byte)30,
                            HP = (byte)35,
                            Special = (byte)50,
                            Species = "Pikachu",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)26,
                            Attack = (byte)90,
                            Defense = (byte)55,
                            HP = (byte)60,
                            Special = (byte)90,
                            Species = "Raichu",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)27,
                            Attack = (byte)75,
                            Defense = (byte)85,
                            HP = (byte)50,
                            Special = (byte)30,
                            Species = "Sandshrew",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)28,
                            Attack = (byte)100,
                            Defense = (byte)110,
                            HP = (byte)75,
                            Special = (byte)55,
                            Species = "Sandslash",
                            Speed = (byte)65
                        },
                        new
                        {
                            PokédexId = (byte)29,
                            Attack = (byte)47,
                            Defense = (byte)52,
                            HP = (byte)55,
                            Special = (byte)40,
                            Species = "Nidoran♀",
                            Speed = (byte)41
                        },
                        new
                        {
                            PokédexId = (byte)30,
                            Attack = (byte)62,
                            Defense = (byte)67,
                            HP = (byte)70,
                            Special = (byte)55,
                            Species = "Nidorina",
                            Speed = (byte)56
                        },
                        new
                        {
                            PokédexId = (byte)31,
                            Attack = (byte)82,
                            Defense = (byte)87,
                            HP = (byte)90,
                            Special = (byte)75,
                            Species = "Nidoqueen",
                            Speed = (byte)76
                        },
                        new
                        {
                            PokédexId = (byte)32,
                            Attack = (byte)57,
                            Defense = (byte)40,
                            HP = (byte)46,
                            Special = (byte)40,
                            Species = "Nidoran♂",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)33,
                            Attack = (byte)72,
                            Defense = (byte)57,
                            HP = (byte)61,
                            Special = (byte)55,
                            Species = "Nidorino",
                            Speed = (byte)65
                        },
                        new
                        {
                            PokédexId = (byte)34,
                            Attack = (byte)92,
                            Defense = (byte)77,
                            HP = (byte)81,
                            Special = (byte)75,
                            Species = "Nidoking",
                            Speed = (byte)85
                        },
                        new
                        {
                            PokédexId = (byte)35,
                            Attack = (byte)45,
                            Defense = (byte)48,
                            HP = (byte)70,
                            Special = (byte)60,
                            Species = "Clefairy",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)36,
                            Attack = (byte)70,
                            Defense = (byte)73,
                            HP = (byte)95,
                            Special = (byte)85,
                            Species = "Clefable",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)37,
                            Attack = (byte)41,
                            Defense = (byte)40,
                            HP = (byte)38,
                            Special = (byte)65,
                            Species = "Vulpix",
                            Speed = (byte)65
                        },
                        new
                        {
                            PokédexId = (byte)38,
                            Attack = (byte)76,
                            Defense = (byte)75,
                            HP = (byte)73,
                            Special = (byte)100,
                            Species = "Ninetales",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)39,
                            Attack = (byte)45,
                            Defense = (byte)20,
                            HP = (byte)115,
                            Special = (byte)25,
                            Species = "Jigglypuff",
                            Speed = (byte)20
                        },
                        new
                        {
                            PokédexId = (byte)40,
                            Attack = (byte)70,
                            Defense = (byte)45,
                            HP = (byte)140,
                            Special = (byte)50,
                            Species = "Wigglytuff",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)41,
                            Attack = (byte)45,
                            Defense = (byte)35,
                            HP = (byte)40,
                            Special = (byte)40,
                            Species = "Zubat",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)42,
                            Attack = (byte)80,
                            Defense = (byte)70,
                            HP = (byte)75,
                            Special = (byte)75,
                            Species = "Golbat",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)43,
                            Attack = (byte)50,
                            Defense = (byte)55,
                            HP = (byte)45,
                            Special = (byte)75,
                            Species = "Oddish",
                            Speed = (byte)30
                        },
                        new
                        {
                            PokédexId = (byte)44,
                            Attack = (byte)65,
                            Defense = (byte)70,
                            HP = (byte)60,
                            Special = (byte)85,
                            Species = "Gloom",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)45,
                            Attack = (byte)80,
                            Defense = (byte)85,
                            HP = (byte)75,
                            Special = (byte)100,
                            Species = "Vileplume",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)46,
                            Attack = (byte)70,
                            Defense = (byte)55,
                            HP = (byte)35,
                            Special = (byte)55,
                            Species = "Paras",
                            Speed = (byte)25
                        },
                        new
                        {
                            PokédexId = (byte)47,
                            Attack = (byte)95,
                            Defense = (byte)80,
                            HP = (byte)60,
                            Special = (byte)80,
                            Species = "Parasect",
                            Speed = (byte)30
                        },
                        new
                        {
                            PokédexId = (byte)48,
                            Attack = (byte)55,
                            Defense = (byte)50,
                            HP = (byte)60,
                            Special = (byte)40,
                            Species = "Venonat",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)49,
                            Attack = (byte)65,
                            Defense = (byte)60,
                            HP = (byte)70,
                            Special = (byte)90,
                            Species = "Venomoth",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)50,
                            Attack = (byte)55,
                            Defense = (byte)25,
                            HP = (byte)10,
                            Special = (byte)45,
                            Species = "Diglett",
                            Speed = (byte)95
                        },
                        new
                        {
                            PokédexId = (byte)51,
                            Attack = (byte)80,
                            Defense = (byte)50,
                            HP = (byte)35,
                            Special = (byte)70,
                            Species = "Dugtrio",
                            Speed = (byte)120
                        },
                        new
                        {
                            PokédexId = (byte)52,
                            Attack = (byte)45,
                            Defense = (byte)35,
                            HP = (byte)40,
                            Special = (byte)40,
                            Species = "Meowth",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)53,
                            Attack = (byte)70,
                            Defense = (byte)60,
                            HP = (byte)65,
                            Special = (byte)65,
                            Species = "Persian",
                            Speed = (byte)115
                        },
                        new
                        {
                            PokédexId = (byte)54,
                            Attack = (byte)52,
                            Defense = (byte)48,
                            HP = (byte)50,
                            Special = (byte)50,
                            Species = "Psyduck",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)55,
                            Attack = (byte)82,
                            Defense = (byte)78,
                            HP = (byte)80,
                            Special = (byte)80,
                            Species = "Golduck",
                            Speed = (byte)85
                        },
                        new
                        {
                            PokédexId = (byte)56,
                            Attack = (byte)80,
                            Defense = (byte)35,
                            HP = (byte)40,
                            Special = (byte)35,
                            Species = "Mankey",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)57,
                            Attack = (byte)105,
                            Defense = (byte)60,
                            HP = (byte)65,
                            Special = (byte)60,
                            Species = "Primeape",
                            Speed = (byte)95
                        },
                        new
                        {
                            PokédexId = (byte)58,
                            Attack = (byte)70,
                            Defense = (byte)45,
                            HP = (byte)55,
                            Special = (byte)50,
                            Species = "Growlithe",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)59,
                            Attack = (byte)110,
                            Defense = (byte)80,
                            HP = (byte)90,
                            Special = (byte)80,
                            Species = "Arcanine",
                            Speed = (byte)95
                        },
                        new
                        {
                            PokédexId = (byte)60,
                            Attack = (byte)50,
                            Defense = (byte)40,
                            HP = (byte)40,
                            Special = (byte)40,
                            Species = "Poliwag",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)61,
                            Attack = (byte)65,
                            Defense = (byte)65,
                            HP = (byte)65,
                            Special = (byte)50,
                            Species = "Poliwhirl",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)62,
                            Attack = (byte)85,
                            Defense = (byte)95,
                            HP = (byte)90,
                            Special = (byte)70,
                            Species = "Poliwrath",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)63,
                            Attack = (byte)20,
                            Defense = (byte)15,
                            HP = (byte)25,
                            Special = (byte)105,
                            Species = "Abra",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)64,
                            Attack = (byte)35,
                            Defense = (byte)30,
                            HP = (byte)40,
                            Special = (byte)120,
                            Species = "Kadabra",
                            Speed = (byte)105
                        },
                        new
                        {
                            PokédexId = (byte)65,
                            Attack = (byte)50,
                            Defense = (byte)45,
                            HP = (byte)55,
                            Special = (byte)135,
                            Species = "Alakazam",
                            Speed = (byte)120
                        },
                        new
                        {
                            PokédexId = (byte)66,
                            Attack = (byte)80,
                            Defense = (byte)50,
                            HP = (byte)70,
                            Special = (byte)35,
                            Species = "Machop",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)67,
                            Attack = (byte)100,
                            Defense = (byte)70,
                            HP = (byte)80,
                            Special = (byte)50,
                            Species = "Machoke",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)68,
                            Attack = (byte)130,
                            Defense = (byte)80,
                            HP = (byte)90,
                            Special = (byte)65,
                            Species = "Machamp",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)69,
                            Attack = (byte)75,
                            Defense = (byte)35,
                            HP = (byte)50,
                            Special = (byte)70,
                            Species = "Bellsprout",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)70,
                            Attack = (byte)90,
                            Defense = (byte)50,
                            HP = (byte)65,
                            Special = (byte)85,
                            Species = "Weepinbell",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)71,
                            Attack = (byte)105,
                            Defense = (byte)65,
                            HP = (byte)80,
                            Special = (byte)100,
                            Species = "Victreebel",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)72,
                            Attack = (byte)40,
                            Defense = (byte)35,
                            HP = (byte)40,
                            Special = (byte)100,
                            Species = "Tentacool",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)73,
                            Attack = (byte)70,
                            Defense = (byte)65,
                            HP = (byte)80,
                            Special = (byte)120,
                            Species = "Tentacruel",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)74,
                            Attack = (byte)80,
                            Defense = (byte)100,
                            HP = (byte)40,
                            Special = (byte)30,
                            Species = "Geodude",
                            Speed = (byte)20
                        },
                        new
                        {
                            PokédexId = (byte)75,
                            Attack = (byte)95,
                            Defense = (byte)115,
                            HP = (byte)55,
                            Special = (byte)45,
                            Species = "Graveler",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)76,
                            Attack = (byte)110,
                            Defense = (byte)130,
                            HP = (byte)80,
                            Special = (byte)55,
                            Species = "Golem",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)77,
                            Attack = (byte)85,
                            Defense = (byte)55,
                            HP = (byte)50,
                            Special = (byte)65,
                            Species = "Ponyta",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)78,
                            Attack = (byte)100,
                            Defense = (byte)70,
                            HP = (byte)65,
                            Special = (byte)80,
                            Species = "Rapidash",
                            Speed = (byte)105
                        },
                        new
                        {
                            PokédexId = (byte)79,
                            Attack = (byte)65,
                            Defense = (byte)65,
                            HP = (byte)90,
                            Special = (byte)40,
                            Species = "Slowpoke",
                            Speed = (byte)15
                        },
                        new
                        {
                            PokédexId = (byte)80,
                            Attack = (byte)75,
                            Defense = (byte)110,
                            HP = (byte)95,
                            Special = (byte)80,
                            Species = "Slowbro",
                            Speed = (byte)30
                        },
                        new
                        {
                            PokédexId = (byte)81,
                            Attack = (byte)35,
                            Defense = (byte)70,
                            HP = (byte)25,
                            Special = (byte)95,
                            Species = "Magnemite",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)82,
                            Attack = (byte)60,
                            Defense = (byte)95,
                            HP = (byte)50,
                            Special = (byte)120,
                            Species = "Magneton",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)83,
                            Attack = (byte)65,
                            Defense = (byte)55,
                            HP = (byte)52,
                            Special = (byte)58,
                            Species = "Farfetch'd",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)84,
                            Attack = (byte)85,
                            Defense = (byte)45,
                            HP = (byte)35,
                            Special = (byte)35,
                            Species = "Doduo",
                            Speed = (byte)75
                        },
                        new
                        {
                            PokédexId = (byte)85,
                            Attack = (byte)110,
                            Defense = (byte)70,
                            HP = (byte)60,
                            Special = (byte)60,
                            Species = "Dodrio",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)86,
                            Attack = (byte)45,
                            Defense = (byte)55,
                            HP = (byte)65,
                            Special = (byte)70,
                            Species = "Seel",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)87,
                            Attack = (byte)70,
                            Defense = (byte)80,
                            HP = (byte)90,
                            Special = (byte)95,
                            Species = "Dewgong",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)88,
                            Attack = (byte)80,
                            Defense = (byte)50,
                            HP = (byte)80,
                            Special = (byte)40,
                            Species = "Grimer",
                            Speed = (byte)25
                        },
                        new
                        {
                            PokédexId = (byte)89,
                            Attack = (byte)105,
                            Defense = (byte)75,
                            HP = (byte)105,
                            Special = (byte)65,
                            Species = "Muk",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)90,
                            Attack = (byte)65,
                            Defense = (byte)100,
                            HP = (byte)30,
                            Special = (byte)45,
                            Species = "Shellder",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)91,
                            Attack = (byte)95,
                            Defense = (byte)180,
                            HP = (byte)50,
                            Special = (byte)85,
                            Species = "Cloyster",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)92,
                            Attack = (byte)35,
                            Defense = (byte)30,
                            HP = (byte)30,
                            Special = (byte)100,
                            Species = "Gastly",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)93,
                            Attack = (byte)50,
                            Defense = (byte)45,
                            HP = (byte)45,
                            Special = (byte)115,
                            Species = "Haunter",
                            Speed = (byte)95
                        },
                        new
                        {
                            PokédexId = (byte)94,
                            Attack = (byte)65,
                            Defense = (byte)60,
                            HP = (byte)60,
                            Special = (byte)130,
                            Species = "Gengar",
                            Speed = (byte)110
                        },
                        new
                        {
                            PokédexId = (byte)95,
                            Attack = (byte)45,
                            Defense = (byte)160,
                            HP = (byte)35,
                            Special = (byte)30,
                            Species = "Onix",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)96,
                            Attack = (byte)48,
                            Defense = (byte)45,
                            HP = (byte)60,
                            Special = (byte)90,
                            Species = "Drowzee",
                            Speed = (byte)42
                        },
                        new
                        {
                            PokédexId = (byte)97,
                            Attack = (byte)73,
                            Defense = (byte)70,
                            HP = (byte)85,
                            Special = (byte)115,
                            Species = "Hypno",
                            Speed = (byte)67
                        },
                        new
                        {
                            PokédexId = (byte)98,
                            Attack = (byte)105,
                            Defense = (byte)90,
                            HP = (byte)30,
                            Special = (byte)25,
                            Species = "Krabby",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)99,
                            Attack = (byte)130,
                            Defense = (byte)115,
                            HP = (byte)55,
                            Special = (byte)50,
                            Species = "Kingler",
                            Speed = (byte)75
                        },
                        new
                        {
                            PokédexId = (byte)100,
                            Attack = (byte)30,
                            Defense = (byte)50,
                            HP = (byte)40,
                            Special = (byte)55,
                            Species = "Voltorb",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)101,
                            Attack = (byte)50,
                            Defense = (byte)70,
                            HP = (byte)60,
                            Special = (byte)80,
                            Species = "Electrode",
                            Speed = (byte)140
                        },
                        new
                        {
                            PokédexId = (byte)102,
                            Attack = (byte)40,
                            Defense = (byte)80,
                            HP = (byte)60,
                            Special = (byte)60,
                            Species = "Exeggcute",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)103,
                            Attack = (byte)95,
                            Defense = (byte)85,
                            HP = (byte)95,
                            Special = (byte)125,
                            Species = "Exeggutor",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)104,
                            Attack = (byte)50,
                            Defense = (byte)95,
                            HP = (byte)50,
                            Special = (byte)40,
                            Species = "Cubone",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)105,
                            Attack = (byte)80,
                            Defense = (byte)110,
                            HP = (byte)60,
                            Special = (byte)50,
                            Species = "Marowak",
                            Speed = (byte)45
                        },
                        new
                        {
                            PokédexId = (byte)106,
                            Attack = (byte)120,
                            Defense = (byte)53,
                            HP = (byte)50,
                            Special = (byte)35,
                            Species = "Hitmonlee",
                            Speed = (byte)87
                        },
                        new
                        {
                            PokédexId = (byte)107,
                            Attack = (byte)105,
                            Defense = (byte)79,
                            HP = (byte)50,
                            Special = (byte)35,
                            Species = "Hitmonchan",
                            Speed = (byte)76
                        },
                        new
                        {
                            PokédexId = (byte)108,
                            Attack = (byte)55,
                            Defense = (byte)75,
                            HP = (byte)90,
                            Special = (byte)60,
                            Species = "Lickitung",
                            Speed = (byte)30
                        },
                        new
                        {
                            PokédexId = (byte)109,
                            Attack = (byte)65,
                            Defense = (byte)95,
                            HP = (byte)40,
                            Special = (byte)60,
                            Species = "Koffing",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)110,
                            Attack = (byte)90,
                            Defense = (byte)120,
                            HP = (byte)65,
                            Special = (byte)85,
                            Species = "Weezing",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)111,
                            Attack = (byte)85,
                            Defense = (byte)95,
                            HP = (byte)80,
                            Special = (byte)30,
                            Species = "Rhyhorn",
                            Speed = (byte)25
                        },
                        new
                        {
                            PokédexId = (byte)112,
                            Attack = (byte)130,
                            Defense = (byte)120,
                            HP = (byte)105,
                            Special = (byte)45,
                            Species = "Rhydon",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)113,
                            Attack = (byte)5,
                            Defense = (byte)5,
                            HP = (byte)250,
                            Special = (byte)105,
                            Species = "Chansey",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)114,
                            Attack = (byte)55,
                            Defense = (byte)115,
                            HP = (byte)65,
                            Special = (byte)100,
                            Species = "Tangela",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)115,
                            Attack = (byte)95,
                            Defense = (byte)80,
                            HP = (byte)105,
                            Special = (byte)40,
                            Species = "Kangaskhan",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)116,
                            Attack = (byte)40,
                            Defense = (byte)70,
                            HP = (byte)30,
                            Special = (byte)70,
                            Species = "Horsea",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)117,
                            Attack = (byte)65,
                            Defense = (byte)95,
                            HP = (byte)55,
                            Special = (byte)95,
                            Species = "Seadra",
                            Speed = (byte)85
                        },
                        new
                        {
                            PokédexId = (byte)118,
                            Attack = (byte)67,
                            Defense = (byte)60,
                            HP = (byte)45,
                            Special = (byte)50,
                            Species = "Goldeen",
                            Speed = (byte)63
                        },
                        new
                        {
                            PokédexId = (byte)119,
                            Attack = (byte)92,
                            Defense = (byte)65,
                            HP = (byte)80,
                            Special = (byte)80,
                            Species = "Seaking",
                            Speed = (byte)68
                        },
                        new
                        {
                            PokédexId = (byte)120,
                            Attack = (byte)45,
                            Defense = (byte)55,
                            HP = (byte)30,
                            Special = (byte)70,
                            Species = "Staryu",
                            Speed = (byte)85
                        },
                        new
                        {
                            PokédexId = (byte)121,
                            Attack = (byte)75,
                            Defense = (byte)85,
                            HP = (byte)60,
                            Special = (byte)100,
                            Species = "Starmie",
                            Speed = (byte)115
                        },
                        new
                        {
                            PokédexId = (byte)122,
                            Attack = (byte)45,
                            Defense = (byte)65,
                            HP = (byte)40,
                            Special = (byte)100,
                            Species = "Mr. Mime",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)123,
                            Attack = (byte)110,
                            Defense = (byte)80,
                            HP = (byte)70,
                            Special = (byte)55,
                            Species = "Scyther",
                            Speed = (byte)105
                        },
                        new
                        {
                            PokédexId = (byte)124,
                            Attack = (byte)50,
                            Defense = (byte)35,
                            HP = (byte)65,
                            Special = (byte)95,
                            Species = "Jynx",
                            Speed = (byte)95
                        },
                        new
                        {
                            PokédexId = (byte)125,
                            Attack = (byte)83,
                            Defense = (byte)57,
                            HP = (byte)65,
                            Special = (byte)85,
                            Species = "Electabuzz",
                            Speed = (byte)105
                        },
                        new
                        {
                            PokédexId = (byte)126,
                            Attack = (byte)95,
                            Defense = (byte)57,
                            HP = (byte)65,
                            Special = (byte)85,
                            Species = "Magmar",
                            Speed = (byte)93
                        },
                        new
                        {
                            PokédexId = (byte)127,
                            Attack = (byte)125,
                            Defense = (byte)100,
                            HP = (byte)65,
                            Special = (byte)55,
                            Species = "Pinsir",
                            Speed = (byte)85
                        },
                        new
                        {
                            PokédexId = (byte)128,
                            Attack = (byte)100,
                            Defense = (byte)95,
                            HP = (byte)75,
                            Special = (byte)70,
                            Species = "Tauros",
                            Speed = (byte)110
                        },
                        new
                        {
                            PokédexId = (byte)129,
                            Attack = (byte)10,
                            Defense = (byte)55,
                            HP = (byte)20,
                            Special = (byte)20,
                            Species = "Magikarp",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)130,
                            Attack = (byte)125,
                            Defense = (byte)79,
                            HP = (byte)95,
                            Special = (byte)100,
                            Species = "Gyarados",
                            Speed = (byte)81
                        },
                        new
                        {
                            PokédexId = (byte)131,
                            Attack = (byte)85,
                            Defense = (byte)80,
                            HP = (byte)130,
                            Special = (byte)95,
                            Species = "Lapras",
                            Speed = (byte)60
                        },
                        new
                        {
                            PokédexId = (byte)132,
                            Attack = (byte)48,
                            Defense = (byte)48,
                            HP = (byte)48,
                            Special = (byte)48,
                            Species = "Ditto",
                            Speed = (byte)48
                        },
                        new
                        {
                            PokédexId = (byte)133,
                            Attack = (byte)55,
                            Defense = (byte)50,
                            HP = (byte)55,
                            Special = (byte)65,
                            Species = "Eevee",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)134,
                            Attack = (byte)65,
                            Defense = (byte)60,
                            HP = (byte)130,
                            Special = (byte)110,
                            Species = "Vaporeon",
                            Speed = (byte)65
                        },
                        new
                        {
                            PokédexId = (byte)135,
                            Attack = (byte)65,
                            Defense = (byte)60,
                            HP = (byte)65,
                            Special = (byte)110,
                            Species = "Jolteon",
                            Speed = (byte)130
                        },
                        new
                        {
                            PokédexId = (byte)136,
                            Attack = (byte)130,
                            Defense = (byte)60,
                            HP = (byte)65,
                            Special = (byte)110,
                            Species = "Flareon",
                            Speed = (byte)65
                        },
                        new
                        {
                            PokédexId = (byte)137,
                            Attack = (byte)60,
                            Defense = (byte)70,
                            HP = (byte)65,
                            Special = (byte)75,
                            Species = "Porygon",
                            Speed = (byte)40
                        },
                        new
                        {
                            PokédexId = (byte)138,
                            Attack = (byte)40,
                            Defense = (byte)100,
                            HP = (byte)35,
                            Special = (byte)90,
                            Species = "Omanyte",
                            Speed = (byte)35
                        },
                        new
                        {
                            PokédexId = (byte)139,
                            Attack = (byte)60,
                            Defense = (byte)125,
                            HP = (byte)70,
                            Special = (byte)115,
                            Species = "Omastar",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)140,
                            Attack = (byte)80,
                            Defense = (byte)90,
                            HP = (byte)30,
                            Special = (byte)45,
                            Species = "Kabuto",
                            Speed = (byte)55
                        },
                        new
                        {
                            PokédexId = (byte)141,
                            Attack = (byte)115,
                            Defense = (byte)105,
                            HP = (byte)60,
                            Special = (byte)70,
                            Species = "Kabutops",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)142,
                            Attack = (byte)105,
                            Defense = (byte)65,
                            HP = (byte)80,
                            Special = (byte)60,
                            Species = "Aerodactyl",
                            Speed = (byte)130
                        },
                        new
                        {
                            PokédexId = (byte)143,
                            Attack = (byte)110,
                            Defense = (byte)65,
                            HP = (byte)160,
                            Special = (byte)65,
                            Species = "Snorlax",
                            Speed = (byte)30
                        },
                        new
                        {
                            PokédexId = (byte)144,
                            Attack = (byte)85,
                            Defense = (byte)100,
                            HP = (byte)90,
                            Special = (byte)125,
                            Species = "Articuno",
                            Speed = (byte)85
                        },
                        new
                        {
                            PokédexId = (byte)145,
                            Attack = (byte)90,
                            Defense = (byte)85,
                            HP = (byte)90,
                            Special = (byte)125,
                            Species = "Zapdos",
                            Speed = (byte)100
                        },
                        new
                        {
                            PokédexId = (byte)146,
                            Attack = (byte)100,
                            Defense = (byte)90,
                            HP = (byte)90,
                            Special = (byte)125,
                            Species = "Moltres",
                            Speed = (byte)90
                        },
                        new
                        {
                            PokédexId = (byte)147,
                            Attack = (byte)64,
                            Defense = (byte)45,
                            HP = (byte)41,
                            Special = (byte)50,
                            Species = "Dratini",
                            Speed = (byte)50
                        },
                        new
                        {
                            PokédexId = (byte)148,
                            Attack = (byte)84,
                            Defense = (byte)65,
                            HP = (byte)61,
                            Special = (byte)70,
                            Species = "Dragonair",
                            Speed = (byte)70
                        },
                        new
                        {
                            PokédexId = (byte)149,
                            Attack = (byte)134,
                            Defense = (byte)95,
                            HP = (byte)91,
                            Special = (byte)100,
                            Species = "Dragonite",
                            Speed = (byte)80
                        },
                        new
                        {
                            PokédexId = (byte)150,
                            Attack = (byte)110,
                            Defense = (byte)90,
                            HP = (byte)106,
                            Special = (byte)154,
                            Species = "Mewtwo",
                            Speed = (byte)130
                        },
                        new
                        {
                            PokédexId = (byte)151,
                            Attack = (byte)100,
                            Defense = (byte)100,
                            HP = (byte)100,
                            Special = (byte)100,
                            Species = "Mew",
                            Speed = (byte)100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
